CONTRIBUTING.md, MAINTAINERS_GUIDE.md
All OCI projects should be bootstrapped with a certain set of files.
Signed-off-by: Chris Aniszczyk <caniszczyk@gmail.com>
=> Add contributing and maintainer guidelines.

CONTRIBUTING.md
For small projects like ocitools a strict requirement would just be
busywork.  And the risk here (a submitted PR that would have been
rejected or redirected in a leader issue) is a risk assumed by the
submitter (who sunk time in the wrong direction) and not much cost to
the maintainers.
Addresses [my ocitools comment][1].
[1]: https://github.com/opencontainers/ocitools/pull/56#discussion_r61934206
=> CONTRIBUTING: Make leader-issues optional

CONTRIBUTING.md
Folks have been dragging this around from the soft limit in
git-commit(1) and git.git's Documentation/SubmittingPatches without
believing it.  Looking at the git.git history through v2.3.4 (git log
--no-merges --format=%s v2.3.4), we have 29853 commits, with 56% ≤ 50
chars and 94% ≤ 70 chars.  Projects that want limits should enforce
them with CI tests (e.g. runtime-spec uses git-validation, which has
[a soft limit at 72 and a hard limit at 90][1]).
See also discussion [here][2].
[1]: https://github.com/vbatts/git-validation/blob/be3aee994370184fd98e455abfe0948d6f45f793/rules/shortsubject/shortsubject.go#L24-L35
[2]: https://github.com/opencontainers/runtime-spec/pull/168#discussion_r39108346
=> CONTRIBUTING: Don't specify a 50-char limit

CONTRIBUTING.md
Small, young projects like ocitools may not have grown a test suite
yet.  Don't make writing a Go test suite a requirement for submitting
a PR.
Also allow for other test frameworks, since Go's framework may not be
the best fit for all projects, which may not even include Go code.
Addresses [my ocitools comment][1].
[1]: https://github.com/opencontainers/ocitools/pull/56#discussion_r61934477
=> CONTRIBUTING: Make the test requirements contingent on an existing suite

CONTRIBUTING.md
For runtime-spec, there are often PRs that pickup and reroll another
user's commits (e.g. opencontainers/runtime-spec#337). As long as the
Signed-off-by entries are there (for the DCO) and the new PR
references the earlier work (to avoid maintainer confusion), I see no
problem with this sort of collaboration.
I thought about replacing the old wording with words like the above
paragraph, but it seemed overly prescriptive.
=> CONTRIBUTING: Allow collaborative pull requests

MAINTAINERS_GUIDE.md
Apart from being a sign of respect to other maintainers, it also ensures
that *all* pull requests get equal amounts of review -- no matter who
wrote them. Maintainers should know better than to make broken
patchsets, but it's also a sign of respect to the community that all
pull requests have equal treatment.
Signed-off-by: Aleksa Sarai <asarai@suse.de>
=> MAINTAINERS: disallow self-LGTMs

.pullapprove.yml
The sign-off requirement catches us up with fcc7f421 (Add contributing and maintainer guidelines, 2016-05-03, #1).  The author ignore catches us up with c82a2e7 (MAINTAINERS: disallow self-LGTMs, 2016-05-27, #13).
The push reset catches us up with opencontainers/runtime-spec@aa9f3a26 (Add PullApprove checks, 2016-05-26, opencontainers/runtime-spec#458), opencontainers/image-spec@95a46754d (Add PullApprove support to enforce review, 2016-06-01, opencontainers/image-spec#101) and opencontainers/runC@e2fd7c11 (Add PullApprove support, 2016-05-26, opencontainers/runC#847).
=> .pullapprove.yml: Reset on push, ignore authors, and require sign-offs

CONTRIBUTING.md, GOVERNANCE.md
This PR is in response to the discussions on the ML about the new
security mailing list and how these documents don't match what
the security@opencontainers.org mailing list should be for.
The security@opencontainers.org mailing list is for *maintainers only*,
and is to be used for technical discussion about potential security
issues. It is not a place for the TOB to have votes about
specification-related business, simply because it is not sane to include
people who are not maintainers of projects in critical security
discussions of said projects.
If in the future we discover that we need to have a place to vote on
security issues, the TOB can do that on their own private mailing list.
For now, we should focus on making sure that security disclosures on
*actual shipping code* is actually …
=> *: clarify how security issues are handled

CONTRIBUTING.md
Extending the earlier softening in #6, because nobody cares about the `XXX-` prefix.  Checking the recent history of all OCI project repos:
$ for REPO in image-spec image-tools runc runtime-spec runtime-tools;
> do
>   (
>     cd "${REPO} &&
>     git fetch origin &&
>     BRANCHES=$(git log --first-parent --oneline origin/master | sed 's/^.* from //') &&
>     echo "${REPO} branches: $(echo "${BRANCHES}" | wc -l)" &&
>     echo "${REPO} numbered: $(echo "${BRANCHES}" | grep '/[0-9]' | wc -l)"
>   );
> done
image-spec branches: 276
image-spec numbered: 1
image-tools branches: 27
image-tools numbered: 0
runc branches: 1299
runc numbered: 21
runtime-spec branches: 391
runtime-spec numbered: 4
runtime-tools branches: 232
runtime-tools numbered: 3
Fixes #26.
=> CONTRIBUTING: Remove branch-naming suggestions

CONTRIBUTING.md
With this change, our content matches:
$ curl http://developercertificate.org/
with the HTML tags removed.
=> CONTRIBUTING: Update Linux Foundation address in the DCO

GOVERNANCE.md
Catching up with opencontainers/tob#18.  I'd rather drop the parenthetical entirely and link to a place that listed OCI Projects, but we don't have a canonical target for that yet (opencontainers/tob#2) and the current closest instance seems to be the GitHub section [here][1] (which doesn't have the "OCI Project"
words).
[1]: https://www.opencontainers.org/community
=> GOVERNANCE: Update project list to include *-tools

.pullapprove.yml
This repository is managed by the union of all OCI Project maintainers.  To avoid having a few active maintainers from one project driving the template in ways that other projects don't support, require at least two approvals from each project.  This will slow down acceptance a bit, but many maintainers belong to multiple projects (and [their votes will count for each group][1]), so you won't need 12 separate maintainers voting to get a single project-template PR across the line.
A side benefit of this is that we no longer need to maintain the tdc-maintainers team.
Also [update][1] from config format v1 to [v2][2] and pull in some new features (which I can spin off into separate PRs if they turn out to be controversial).
[1]: http://docs.pullapprove.com/migrating-to-v2/
[2]: …
=> .pullapprove.yml: List project maintainers separately

GOVERNANCE.md
Catching up with opencontainers/tob#29 and the [subsequent rename][1].
I'd still rather drop the parenthetical entirely and link to a place that listed OCI Projects, but we don't have a canonical target for that yet (opencontainers/tob#2) and the current closest instance seems to be the GitHub section in [2] (which doesn't have the "OCI Project" words).
Like #24.
@caniszczyk, it looks like [the opencontainers.org page][2] still needs “go-selinux” → “selinux”.
[1]: https://github.com/opencontainers/selinux/issues/6#issuecomment-285428099
[2]: https://www.opencontainers.org/community
=> GOVERNANCE: List selinux project

MAINTAINERS_GUIDE.md
Cherry-picked from #20, because there was more discussion in today's meeting about dropping this role, but we haven't been able to move forward with #20 as a whole.  Cc @caniszczyk.
Hooray institutions ;).  Because `GOVERNANCE.md` is already making decisions with a ⅔ vote, there's no reason to appeal to the TOB (the old ⅔ vote for appeal is now sufficient for making the decision outright).
[All current OCI Projects have adopted the GOVERNANCE docs][1] (although runc has yet to actually merge them into its repository) so I think this approach is portable while [the Chief Maintainer approach was not][2].  Taking the runc maintainer subset of that vote (just to be sure the doc applies to runc):
* `+7`: Aleksa Sarai, Alexander Morozov, Daniel Dao, Mrunal Patel, Qiang Huang, Rohit Jnagal, …
=> MAINTAINERS_GUIDE: Replace Chief Maintainer with GOVERNANCE

MAINTAINERS
Currently the OCI seems to have one repository per Project.  A few repositories are not official projects; for example, [artwork][2] may never be a Project.  But I expect that going forward, any opencontainers/ repos that have a `MAINTAINERS` file will be official Projects, so the union rule here should be both correct and easy to maintain.
The file is not Markdown, so I've gone with my usual reference-style link instead of a Markdown reference-style link.
[2]: https://github.com/opencontainers/artwork
=> MAINTAINERS: Explain the format and reference other projects

CONTRIBUTING.md
The other headers only have a single blank line before them.
=> CONTRIBUTING: Remove extra blank line before "Conventions"

CONTRIBUTING.md
So far dev@ volume has been low enough that [we haven't needed per-project lists][1], so we can add it in this central location.  In the event that we do split lists later, the reference-style link makes it easy for projects to update the target without touching the line with the link text.  The meetings and IRC channel are in the same boat (not enought traffic to be worth splitting).  The content I'm adding here is adapted from [here][2] and [here][3].  As long as the meeting is shared, linking the runtime-spec maintained meeting.ics seemed easier than keeping a parallel copy here.
The CoC titles itself "OpenContainers Code of Conduct", but [opencontainers.org][4] has:
> Connecting with the Open Container Initiative community
And I feel like I've been seeing the singular, spaced form …
=> CONTRIBUTING: Code of conduct, meetings, mailing list, and IRC

CONTRIBUTING.md
Not all OCI Projects are primarily Go, and filling in off-topic formatting advice doesn't seem useful.  One approach to this would be to require projects to support `make fmt` to handle any auto-formatting.  But an easier approach is to keep the document [generic in this repository][1], and allow downstream projects to add their own project-specific content as they see fit.  I don't expect a lot of churn in this document, so there shouldn't be many conflicts between those downstream changes and further project-template development.
[1]: https://github.com/opencontainers/project-template/issues/4#issuecomment-221081999
=> CONTRIBUTING: Remove gofmt advice

CONTRIBUTING.md
Current [runtime-tools docs for the man pages are under man/][0].  No docs for building them yet beyond the Makefile rule, and that may be all we need ;).  Because there is no downstream consensus on doc locations, remove the reference.  Downstream repositories can add it (or similar content) back in [as they see fit][1].  I don't expect a lot of churn in this document, so there shouldn't be many conflicts between those downstream changes and further project-template development.
[0]: https://github.com/opencontainers/runtime-tools/tree/v0.5.0/man
[1]: https://github.com/opencontainers/project-template/issues/4#issuecomment-221081999
=> CONTRIBUTING: Remove docs/README.md reference

MAINTAINERS_GUIDE.md
If we wanted to enumerate these we should use Markdown's enumerated list.  But these aren't ordered, so remove the old enumerations.
Also adjust one line per sentence, since that's the standard in other OCI projects (like [the runtime spec][1]).
[1]: https://github.com/opencontainers/runtime-spec/blob/v1.0.1/style.md#one-sentence-per-line
=> MAINTAINERS_GUIDE: Remove enumeratations for responsibilities

MAINTAINERS_GUIDE.md
This information was already covered more explicitly in the earlier “What are a maintainer's responsibilities?” section.
=> MAINTAINERS_GUIDE: Remove duplicate maintainer expectations

MAINTAINERS_GUIDE.md
The old wording did not mention email discussion before working up changes, which we [often recommend][2] to avoid contributors sinking a lot of work into a pull request that ends up being rejected because of a fundamental design issue.  The new wording mentions that and also:
* Removes the overly compact short answer to [avoid confusion][3].  The section is not so long that it needs a one-line summary.
* Distinguishes between in-PR votes (LGTM/Rejected) and merging/closing the PR.
* Mentions GOVERNANCE for management changes.
* Uses an enumerated list instead of “Step N” text.
* Uses one line per sentence.
[2]: https://github.com/opencontainers/runtime-spec/pull/420#discussion_r61972422
[3]: https://github.com/opencontainers/runtime-spec/pull/420#discussion_r61973030
=> MAINTAINERS_GUIDE: Mention email in "How are decisions made?"

README.md
Use links, which gives us a bit more space to discuss the content while still making the filename discoverable.
=> README: Update list of content

.pullapprove.yml
Other projects may refer to template's pullapprove config file.
I think we'd better based on pullapprove's document.
This will reduce doubts of pullapprove grammar.
Signed-off-by: Ma Shimiao <mashimiao.fnst@cn.fujitsu.com>
=> small fix based on pullapprove document

RELEASES.md
Picking up Ma Shimiao's [change][1] from opencontainers/runtime-spec#937, this gives us consistent bullet characters for all items in this list.
[1]: https://github.com/opencontainers/runtime-spec/pull/937/files#diff-5cafcf46bfb947f8e58fa5c16d39018cL49
=> RELEASES: Use an asterix bullet for "Minor and patch releases..."

CONTRIBUTING.md
This should have been added along with the consuming reference-style link in ee72bc89 (#45).
=> CONTRIBUTING: Add rfc5545 link label (fixing a broken link)
